version: "2"

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./mysql_data:/var/lib/mysql"
  main:
    build: .
    volumes:
      - "local_bundle:/usr/local/bundle"
      - "./brimir_data:/opt/brimir/data"
    depends_on:
      - mysql
    environment:
      - RAILS_ENV=production
      - DOMAIN=209.9.106.239
      - SECRET_KEY_BASE=e994b40fb5baa9afc789d57a2c181810c33b300768d609c8531278269571962aa51001b05d78536cda3bb868e9796214fe9e9d6d8f87824b0b92cc07369fd7d0
    ports:
      - 80:80
volumes:
  local_bundle:

