default: &default
  adapter: mysql2
  collation: utf8mb4_bin
  database: app_prd
  encoding: utf8mb4
  host: <%= ENV.fetch("MYSQL_HOST") { "mysql" } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { "root" } %>
  pool: 5
  username: <%= ENV.fetch("MYSQL_USERNAME") { "root" } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
